# Calamares Welcome Module Configuration
---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: true
showDonateUrl: false

requirements:
    requiredStorage: 15.0
    requiredRam: 2.0
    internetCheckUrl: http://deb.debian.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root

geoip:
    style: "none"
